#- hosts: all
# gather_facts: true
# become: true
# tasks:
   - name: Create Network
     docker_network:
       name: app-network
       state: present
     vars:
       ansible_python_interpreter: /opt/docker_venv/bin/python3
