name: CI DevOps 2024

on:
  # To begin, you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B package --file simple-api/pom.xml

      # Run tests with Maven
      - name: Run tests with Maven
        run: mvn test

     

     
