name: CI devops 2024

on:
  # Trigger the workflow on pushes and pull requests to main and dev branches
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Step to checkout the source code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Step to set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'correcto'  # Specify the Java distribution

      # Step to build and test the application with Maven
      - name: Build and test with Maven
        run: mvn clean verify
