name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: 
      - main 
      - develop
jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
    - name: vh
     

     
